token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
server_id: "1322191259997048845"

config:
  verification:
    role_id_to_use_verification_command: "1322194832520646696"
    prefix: "!verification"
    title: null
    content:
      - "### Mushroom Verification"
      - "**Hello  <:hello:1324141222079631411>**,"
      - "this channel is to verify if you are real"
      - "press this button to verify yourself"
      - ""
      - "-# Don't forget read the rules to avoid being banned"
    thumbnail: null
    image: null
    color: "#eb5b44"
    text_button: "✅ Verify your account"
    verify_message: "You have verified successfully yourself ✅"
    role_id_to_add: "1322193727220875337"
  welcome:
    channel_id: "1322202447883669617"
    title: null
    content:
      - "### ¡%user% Welcome to Mushroom server!"
      - ""
      - "We hope you have a good experience and meet"
      - "new people here."
      - ""
      - "Don't **forget** read the <#1322201895862931558> to avoid"
      - "being banned."
      - ""
      - "-# user invited by %invited_by_id% ・ member number %member_number%"
    thumbnail: "%user_thumbnail%"
    image: "https://cdn.discordapp.com/attachments/1322898427486670962/1322930998887055482/welcome_server.png?ex=67769f81&is=67754e01&hm=49c4b8a4c65e0ef119136b22b0b117e456e0bfb164e4ba5103e045b676ca1899&"
    color: "#eb5b44"
  status:
    elapsed_time: 10
    states:
      - state: "Developed by lsEmpty"
        type: "none"
      - state: "%users% users 👀"
        type: "%watching%"
      - state: "Minecraft"
        type: "%playing%"
  suggestion:
    add:
      suggestion_channel_id: "1322205879281389620"
      role_id_with_permissions_to_write_in_suggestion_channel: "1322571610426834954"
      emoji_check: "<:check:1322933767215517706>"
      emoji_no_check: "<:no_check:1322933782759608420>"
      prefix: "!suggestion"
      embed_color: "#eb5b44"
      title: "<:zelda_sword:1323003596219879444>  **NEW SUGGESTION**"
      description: "has created a suggestion."
      head_field: "**Suggestion:**"
      footer: "new suggestion"
    change_state:
      role_id_with_permissions_to_change_suggestion_state: "1322571610426834954"
      channel_id_to_set_change_state: "1322525455269625916"
      channels:
        - "1322205879281389620"
        - "1322525455269625916"
      states:
        accepted:
          emoji: "✅"
          title: "<:check:1322933767215517706>  **SUGGESTION ACCEPTED**"
          description: "suggestion has been accepted"
          footer: "new change • suggestion changed by"
          color: "#c4ff7d"
        denied:
          emoji: "⛔"
          title: "<:no_check:1322933782759608420>  **SUGGESTION DENIED**"
          description: "suggestion has been denied"
          footer: "new change • suggestion changed by"
          color: "#919191"
        implemented:
          emoji: "🍄"
          title: "<:mushroom:1322886720051482624>  **SUGGESTION IMPLEMENTED**"
          description: "suggestion has been implemented"
          footer: "new change • suggestion changed by"
          color: "#eb5b44"
  embed:
    role_id_permissions: "1322571610426834954"